import User.IPhoneRobot;
import User.Person;
import model.IPhone;
import model.Mobile;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Mobile iphone = new IPhone("iPhone Name", "Red", "iPhone brand");
        Person person = new Person("Lester");
        System.out.println(iphone.call("Labaybebe"));
        System.out.println(iphone.getMobileInfo());
        System.out.println(person.makeCall(iphone, "qwergthujimksafsdfgsdgfgsfdgdfhdfhgfdg"));


        IPhoneRobot iphonerobot = new IPhoneRobot();
        IPhone phone = new IPhone("iPhone Name", "Red", "iPhone brand"); // phone should reference to IPhone else compile error
        System.out.println(iphonerobot.makeCall(phone, "qwergthujimksafsdfgsdgfgsfdgdfhdfhgfdg"));
    }
}
