import model.IPhone;
import model.Mobile;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
        Mobile iphone = new IPhone();
        System.out.println(iphone.call("Labaybebe"));
    }
}
